<?php
$pageTitle = 'My Payslips | Hotela';
ob_start();
?>
<section class="card">
    <header class="payslip-header">
        <div>
            <h2>My Payslips</h2>
            <p class="payslip-subtitle">View and download your payslip history</p>
        </div>
    </header>

    <?php if (empty($payslips)): ?>
        <div class="empty-state">
            <svg class="empty-icon" width="64" height="64" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5">
                <rect x="2" y="4" width="20" height="18" rx="2" ry="2"></rect>
                <line x1="2" y1="8" x2="22" y2="8"></line>
                <line x1="6" y1="4" x2="6" y2="8"></line>
            </svg>
            <h3>No Payslips Available</h3>
            <p>You don't have any payslips yet. Payslips will appear here once they are generated by the finance department.</p>
        </div>
    <?php else: ?>
        <div class="payslips-list">
            <?php foreach ($payslips as $payslip): ?>
                <div class="payslip-card">
                    <div class="payslip-card-header">
                        <div class="payslip-info">
                            <h3 class="payslip-period">
                                <?= date('F Y', strtotime($payslip['pay_period_end'])); ?>
                            </h3>
                            <p class="payslip-dates">
                                <?= date('M j', strtotime($payslip['pay_period_start'])); ?> - 
                                <?= date('M j, Y', strtotime($payslip['pay_period_end'])); ?>
                            </p>
                        </div>
                        <div class="payslip-amount">
                            <span class="amount-label">Net Salary</span>
                            <span class="amount-value">KES <?= number_format((float)$payslip['net_salary'], 2); ?></span>
                        </div>
                    </div>
                    <div class="payslip-card-body">
                        <div class="payslip-details">
                            <div class="detail-item">
                                <span class="detail-label">Basic Salary</span>
                                <span class="detail-value">KES <?= number_format((float)$payslip['basic_salary'], 2); ?></span>
                            </div>
                            <div class="detail-item">
                                <span class="detail-label">Allowances</span>
                                <span class="detail-value detail-positive">+KES <?= number_format((float)$payslip['allowances'], 2); ?></span>
                            </div>
                            <div class="detail-item">
                                <span class="detail-label">Deductions</span>
                                <span class="detail-value detail-negative">-KES <?= number_format((float)$payslip['deductions'], 2); ?></span>
                            </div>
                        </div>
                        <div class="payslip-status">
                            <span class="status-badge status-<?= strtolower($payslip['status']); ?>">
                                <?= htmlspecialchars(ucfirst($payslip['status'])); ?>
                            </span>
                        </div>
                    </div>
                    <div class="payslip-card-footer">
                        <a href="<?= base_url('dashboard/payslip/view?id=' . (int)$payslip['id']); ?>" class="btn btn-outline btn-small">
                            <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                                <path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"></path>
                                <circle cx="12" cy="12" r="3"></circle>
                            </svg>
                            View Details
                        </a>
                    </div>
                </div>
            <?php endforeach; ?>
        </div>
    <?php endif; ?>
</section>

<style>
.payslip-header {
    margin-bottom: 2rem;
    padding-bottom: 1.5rem;
    border-bottom: 1px solid #e2e8f0;
}

.payslip-header h2 {
    margin: 0 0 0.25rem 0;
    font-size: 1.75rem;
    font-weight: 700;
    color: var(--dark);
}

.payslip-subtitle {
    margin: 0;
    font-size: 0.95rem;
    color: #64748b;
}

.payslips-list {
    display: flex;
    flex-direction: column;
    gap: 1.25rem;
}

.payslip-card {
    background: #fff;
    border: 1px solid #e2e8f0;
    border-radius: 0.75rem;
    padding: 1.5rem;
    transition: all 0.2s ease;
}

.payslip-card:hover {
    border-color: var(--primary);
    box-shadow: 0 4px 12px rgba(0, 0, 0, 0.05);
}

.payslip-card-header {
    display: flex;
    justify-content: space-between;
    align-items: flex-start;
    margin-bottom: 1.25rem;
    padding-bottom: 1.25rem;
    border-bottom: 1px solid #f1f5f9;
}

.payslip-period {
    margin: 0 0 0.25rem 0;
    font-size: 1.125rem;
    font-weight: 600;
    color: var(--dark);
}

.payslip-dates {
    margin: 0;
    font-size: 0.875rem;
    color: #64748b;
}

.payslip-amount {
    text-align: right;
}

.amount-label {
    display: block;
    font-size: 0.75rem;
    font-weight: 500;
    color: #64748b;
    text-transform: uppercase;
    letter-spacing: 0.05em;
    margin-bottom: 0.25rem;
}

.amount-value {
    display: block;
    font-size: 1.5rem;
    font-weight: 700;
    color: var(--primary);
}

.payslip-card-body {
    display: flex;
    justify-content: space-between;
    align-items: flex-end;
    margin-bottom: 1.25rem;
}

.payslip-details {
    display: flex;
    flex-direction: column;
    gap: 0.75rem;
    flex: 1;
}

.detail-item {
    display: flex;
    justify-content: space-between;
    align-items: center;
}

.detail-label {
    font-size: 0.875rem;
    color: #64748b;
}

.detail-value {
    font-size: 0.95rem;
    font-weight: 600;
    color: var(--dark);
}

.detail-value.detail-positive {
    color: #16a34a;
}

.detail-value.detail-negative {
    color: #dc2626;
}

.status-badge {
    display: inline-flex;
    align-items: center;
    padding: 0.375rem 0.75rem;
    border-radius: 0.25rem;
    font-size: 0.75rem;
    font-weight: 600;
    text-transform: capitalize;
}

.status-badge.status-pending {
    background: #fef3c7;
    color: #f59e0b;
}

.status-badge.status-processed {
    background: #dbeafe;
    color: #2563eb;
}

.status-badge.status-paid {
    background: #dcfce7;
    color: #16a34a;
}

.status-badge.status-cancelled {
    background: #fee2e2;
    color: #dc2626;
}

.payslip-card-footer {
    padding-top: 1.25rem;
    border-top: 1px solid #f1f5f9;
}

.empty-state {
    text-align: center;
    padding: 4rem 2rem;
}

.empty-icon {
    color: #cbd5e1;
    margin-bottom: 1.5rem;
}

.empty-state h3 {
    margin: 0 0 0.5rem 0;
    font-size: 1.25rem;
    font-weight: 600;
    color: var(--dark);
}

.empty-state p {
    margin: 0;
    color: #64748b;
}
</style>

<?php
$slot = ob_get_clean();
include view_path('layouts/dashboard.php');
?>

