<?php

return [
    "CREATE TABLE IF NOT EXISTS attendance_logs (
        id INT AUTO_INCREMENT PRIMARY KEY,
        user_id INT NOT NULL,
        check_in_time DATETIME NOT NULL,
        check_out_time DATETIME NULL,
        checked_in_by INT NULL COMMENT 'Security staff who checked them in',
        checked_out_by INT NULL COMMENT 'Security staff who checked them out',
        status ENUM('present', 'checked_out') DEFAULT 'present',
        notes TEXT NULL,
        override_granted_by INT NULL COMMENT 'Admin/Director who granted override',
        override_expires_at DATETIME NULL COMMENT 'When override expires',
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
        INDEX idx_user (user_id),
        INDEX idx_status (status),
        INDEX idx_check_in (check_in_time),
        INDEX idx_check_out (check_out_time),
        INDEX idx_override (override_expires_at),
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
        FOREIGN KEY (checked_in_by) REFERENCES users(id) ON DELETE SET NULL,
        FOREIGN KEY (checked_out_by) REFERENCES users(id) ON DELETE SET NULL,
        FOREIGN KEY (override_granted_by) REFERENCES users(id) ON DELETE SET NULL
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
    
    "CREATE TABLE IF NOT EXISTS duty_rosters (
        id INT AUTO_INCREMENT PRIMARY KEY,
        title VARCHAR(255) NOT NULL,
        period_type ENUM('weekly', 'monthly') NOT NULL,
        start_date DATE NOT NULL,
        end_date DATE NOT NULL,
        status ENUM('draft', 'published', 'archived') DEFAULT 'draft',
        created_by INT NOT NULL,
        published_at DATETIME NULL,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
        INDEX idx_period (start_date, end_date),
        INDEX idx_status (status),
        INDEX idx_created_by (created_by),
        FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE RESTRICT
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
    
    "CREATE TABLE IF NOT EXISTS roster_assignments (
        id INT AUTO_INCREMENT PRIMARY KEY,
        roster_id INT NOT NULL,
        user_id INT NOT NULL,
        shift_date DATE NOT NULL,
        shift_start_time TIME NOT NULL,
        shift_end_time TIME NOT NULL,
        role_key VARCHAR(50) NOT NULL COMMENT 'Role for this shift',
        location VARCHAR(255) NULL COMMENT 'Location/department assignment',
        notes TEXT NULL,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
        UNIQUE KEY unique_user_shift (roster_id, user_id, shift_date, shift_start_time),
        INDEX idx_roster (roster_id),
        INDEX idx_user (user_id),
        INDEX idx_shift_date (shift_date),
        INDEX idx_role (role_key),
        FOREIGN KEY (roster_id) REFERENCES duty_rosters(id) ON DELETE CASCADE,
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
    
    "CREATE TABLE IF NOT EXISTS workflow_tasks (
        id INT AUTO_INCREMENT PRIMARY KEY,
        task_type VARCHAR(50) NOT NULL COMMENT 'housekeeping, maintenance, inventory, guest_service',
        title VARCHAR(255) NOT NULL,
        description TEXT NULL,
        priority ENUM('low', 'normal', 'high', 'urgent') DEFAULT 'normal',
        status ENUM('pending', 'assigned', 'in_progress', 'completed', 'cancelled', 'escalated') DEFAULT 'pending',
        assigned_to INT NULL COMMENT 'Staff member assigned',
        assigned_by INT NULL COMMENT 'Who assigned the task',
        department VARCHAR(50) NULL COMMENT 'Target department',
        location VARCHAR(255) NULL COMMENT 'Location/room/item',
        due_date DATETIME NULL,
        completed_at DATETIME NULL,
        completed_by INT NULL,
        workflow_step INT DEFAULT 1 COMMENT 'Current step in workflow',
        workflow_data JSON NULL COMMENT 'Additional workflow data',
        related_id INT NULL COMMENT 'Related booking/room/inventory item',
        related_type VARCHAR(50) NULL COMMENT 'Type of related entity',
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
        INDEX idx_type (task_type),
        INDEX idx_status (status),
        INDEX idx_assigned_to (assigned_to),
        INDEX idx_department (department),
        INDEX idx_priority (priority),
        INDEX idx_due_date (due_date),
        INDEX idx_workflow_step (workflow_step),
        INDEX idx_related (related_type, related_id),
        FOREIGN KEY (assigned_to) REFERENCES users(id) ON DELETE SET NULL,
        FOREIGN KEY (assigned_by) REFERENCES users(id) ON DELETE SET NULL,
        FOREIGN KEY (completed_by) REFERENCES users(id) ON DELETE SET NULL
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
    
    "CREATE TABLE IF NOT EXISTS workflow_approvals (
        id INT AUTO_INCREMENT PRIMARY KEY,
        task_id INT NOT NULL,
        step_number INT NOT NULL,
        approver_role VARCHAR(50) NOT NULL COMMENT 'Role required to approve',
        approver_id INT NULL COMMENT 'User who approved',
        status ENUM('pending', 'approved', 'rejected', 'skipped') DEFAULT 'pending',
        notes TEXT NULL,
        approved_at DATETIME NULL,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
        INDEX idx_task (task_id),
        INDEX idx_step (step_number),
        INDEX idx_status (status),
        INDEX idx_approver (approver_id),
        FOREIGN KEY (task_id) REFERENCES workflow_tasks(id) ON DELETE CASCADE,
        FOREIGN KEY (approver_id) REFERENCES users(id) ON DELETE SET NULL
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
    
    "CREATE TABLE IF NOT EXISTS workflow_notifications (
        id INT AUTO_INCREMENT PRIMARY KEY,
        task_id INT NOT NULL,
        user_id INT NOT NULL,
        notification_type VARCHAR(50) NOT NULL COMMENT 'assigned, approved, completed, escalated',
        message TEXT NOT NULL,
        read_at DATETIME NULL,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        INDEX idx_task (task_id),
        INDEX idx_user (user_id),
        INDEX idx_read (read_at),
        INDEX idx_type (notification_type),
        FOREIGN KEY (task_id) REFERENCES workflow_tasks(id) ON DELETE CASCADE,
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci"
];

